In [ ]:
!pip install tensorflow_hub librosa


In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import librosa
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical


In [ ]:
yamnet = hub.load("https://tfhub.dev/google/yamnet/1")


In [ ]:
def extract_embedding(file):
    wav, sr = librosa.load(file, sr=16000)
    wav = wav.astype(np.float32)

    scores, embeddings, _ = yamnet(wav)
    return tf.reduce_mean(embeddings, axis=0).numpy()


In [ ]:
DATASET_PATH = "/content/audio_dataset"

X = []
y = []

for label in os.listdir(DATASET_PATH):
    folder = os.path.join(DATASET_PATH, label)
    for file in os.listdir(folder):
        path = os.path.join(folder, file)
        emb = extract_embedding(path)
        X.append(emb)
        y.append(label)

X = np.array(X)
y = np.array(y)

print(X.shape)


FileNotFoundError: [Errno 2] No such file or directory: '/content/audio_dataset'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unzip TESS.zip


unzip:  cannot find or open TESS.zip, TESS.zip.zip or TESS.zip.ZIP.


In [ ]:
!ls


drive  sample_data


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls /content/drive/MyDrive


 1nt23is047Bhagyajyoti.ipynb
 1NT23IS047.pptx
 1nt23is047_SecA_lab5.gdoc
 1NT23IS049_Sec_A_lab_7.gdoc
 Bhagyajyoti_G_80038.pdf
 Bprg1.png
 Bprg2.png
 Classroom
'Colab Notebooks'
'final year project'
 la1.1.pdf
 la1.2.pdf
 la2.1.pdf
 la2.2.pdf
'llm(tutorial4).pdf'
 Screenshot_2024-10-25-14-39-20-33_40deb401b9ffe8e1df2f1cc5ba480b12.jpg
'SE-LAbActicity-Template. (1).gdoc'
'SE-LAbActicity-Template.(1).gdoc'
'SE-LAbActicity-Template. (2).gdoc'
 SE-LAbActicity-Template..gdoc
'Untitled document.gdoc'


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls "/content/drive/MyDrive/final year project"


 dataset  'TESS Toronto emotional speech set data'


In [ ]:
!unzip "/content/drive/MyDrive/final year project/TESS Toronto Emotional Speech Set.zip" -d /content/


unzip:  cannot find or open /content/drive/MyDrive/final year project/TESS Toronto Emotional Speech Set.zip, /content/drive/MyDrive/final year project/TESS Toronto Emotional Speech Set.zip.zip or /content/drive/MyDrive/final year project/TESS Toronto Emotional Speech Set.zip.ZIP.


In [ ]:
!ls "/content/drive/MyDrive/final year project"


 dataset  'TESS Toronto emotional speech set data'


In [ ]:
DATASET_PATH = "/content/drive/MyDrive/final year project/TESS Toronto emotional speech set data"


In [ ]:
import os
print(os.listdir(DATASET_PATH))


['YAF_neutral', 'YAF_disgust', 'YAF_happy', 'YAF_sad', 'YAF_pleasant_surprised', 'YAF_fear', 'TESS Toronto emotional speech set data']


In [ ]:
!pip install tensorflow tensorflow_hub librosa


In [ ]:
import os
import librosa
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

DATASET_PATH = "/content/drive/MyDrive/final year project/TESS Toronto emotional speech set data"

yamnet = hub.load("https://tfhub.dev/google/yamnet/1")

X = []
y = []

for emotion in os.listdir(DATASET_PATH):
    folder = os.path.join(DATASET_PATH, emotion)

    for file in os.listdir(folder):
        path = os.path.join(folder, file)

        audio, sr = librosa.load(path, sr=16000)
        scores, embeddings, _ = yamnet(audio)

        X.append(np.mean(embeddings.numpy(), axis=0))
        y.append(emotion)

X = np.array(X)
y = np.array(y)

le = LabelEncoder()
y = to_categorical(le.fit_transform(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = Sequential([
    Dense(256, activation='relu', input_shape=(1024,)),
    Dense(128, activation='relu'),
    Dense(y.shape[1], activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=16)

loss, acc = model.evaluate(X_test, y_test)
print("Accuracy:", acc)


/tmp/ipython-input-2204346138.py:25: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sr = librosa.load(path, sr=16000)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


IsADirectoryError: [Errno 21] Is a directory: '/content/drive/MyDrive/final year project/TESS Toronto emotional speech set data/TESS Toronto emotional speech set data/OAF_Sad'

In [ ]:
import os
import librosa
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

DATASET_PATH = "/content/drive/MyDrive/final year project/TESS Toronto emotional speech set data/TESS Toronto emotional speech set data"

yamnet = hub.load("https://tfhub.dev/google/yamnet/1")

X = []
y = []

for emotion_folder in os.listdir(DATASET_PATH):
    emotion_path = os.path.join(DATASET_PATH, emotion_folder)

    if os.path.isdir(emotion_path):

        emotion = emotion_folder.split("_")[-1]   # Sad, Happy, Angry...

        for file in os.listdir(emotion_path):

            if file.endswith(".wav"):

                path = os.path.join(emotion_path, file)

                audio, sr = librosa.load(path, sr=16000)

                scores, embeddings, _ = yamnet(audio)

                X.append(np.mean(embeddings.numpy(), axis=0))
                y.append(emotion)

X = np.array(X)
y = np.array(y)

le = LabelEncoder()
y = to_categorical(le.fit_transform(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = Sequential([
    Dense(256, activation='relu', input_shape=(1024,)),
    Dense(128, activation='relu'),
    Dense(y.shape[1], activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=15, batch_size=16)

loss, acc = model.evaluate(X_test, y_test)
print("Accuracy:", acc)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.5417 - loss: 1.4033
Epoch 2/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8819 - loss: 0.3726
Epoch 3/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9240 - loss: 0.2288
Epoch 4/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9503 - loss: 0.1785
Epoch 5/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9559 - loss: 0.1388
Epoch 6/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9556 - loss: 0.1231
Epoch 7/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9767 - loss: 0.0806
Epoch 8/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9804 - loss: 0.0723
Epoch 9/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9523 - loss: 0.1090
Epoch 10/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9791 - loss: 0.0538
Epoch 11/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9836 - loss: 0.0469
Epoch 12/15
140/140 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [ ]:
import numpy as np

y_pred = model.predict(X_test)

# convert from one-hot
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)


18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

acc = accuracy_score(y_true_classes, y_pred_classes)
prec = precision_score(y_true_classes, y_pred_classes, average='weighted')
rec = recall_score(y_true_classes, y_pred_classes, average='weighted')
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')

print("Accuracy :", acc)
print("Precision:", prec)
print("Recall   :", rec)
print("F1 Score :", f1)


Accuracy : 0.9553571428571429
Precision: 0.9588467575368723
Recall   : 0.9553571428571429
F1 Score : 0.955031604109949


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(y_true_classes, y_pred_classes)
print(cm)

print(classification_report(y_true_classes, y_pred_classes, target_names=le.classes_))


[[44  0  1  0  1  0  0  0  0  0]
 [ 0 37  0  0  0  0  1  0  0  0]
 [ 2  0 71  1  1  1  0  0  0  0]
 [ 0  1  0 77  0  0  0  0  1  0]
 [ 0  0  0  1 41  0  0  0  0  0]
 [ 0  0  2  0  2 56  0  0  9  1]
 [ 0  0  0  0  0  0 86  0  0  0]
 [ 0  0  0  0  0  0  0 42  0  0]
 [ 0  0  0  0  0  0  0  0 41  0]
 [ 0  0  0  0  0  0  0  0  0 40]]
              precision    recall  f1-score   support

        Fear       0.96      0.96      0.96        46
         Sad       0.97      0.97      0.97        38
       angry       0.96      0.93      0.95        76
     disgust       0.97      0.97      0.97        79
        fear       0.91      0.98      0.94        42
       happy       0.98      0.80      0.88        70
     neutral       0.99      1.00      0.99        86
         sad       1.00      1.00      1.00        42
    surprise       0.80      1.00      0.89        41
   surprised       0.98      1.00      0.99        40

    accuracy                           0.96       560
   macro avg       

In [ ]:
y_all_pred = model.predict(X)
y_all_pred_classes = np.argmax(y_all_pred, axis=1)
y_all_true_classes = np.argmax(y, axis=1)

overall_acc = accuracy_score(y_all_true_classes, y_all_pred_classes)

print("Overall Dataset Accuracy:", overall_acc)


88/88 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Overall Dataset Accuracy: 0.9867857142857143


In [ ]:
import librosa
import numpy as np

def predict_emotion(audio_path):
    audio, sr = librosa.load(audio_path, sr=16000)

    # YAMNet embeddings
    scores, embeddings, _ = yamnet(audio)

    feature = np.mean(embeddings.numpy(), axis=0)
    feature = feature.reshape(1, -1)

    pred = model.predict(feature)

    predicted_class = np.argmax(pred)
    emotion = le.inverse_transform([predicted_class])[0]

    confidence = np.max(pred)

    print("Predicted Emotion:", emotion)
    print("Confidence:", confidence)

    return emotion


In [ ]:
predict_emotion("/mnt/data/e13a7456-5fb7-46b0-ae98-b682a35c2b1c.wav")


/tmp/ipython-input-3852858702.py:5: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sr = librosa.load(audio_path, sr=16000)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/e13a7456-5fb7-46b0-ae98-b682a35c2b1c.wav'

In [ ]:
!apt-get install ffmpeg


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.


In [ ]:
!ffmpeg -i /mnt/data/e13a7456-5fb7-46b0-ae98-b682a35c2b1c.wav /content/test_clean.wav


ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

In [ ]:
predict_emotion("/content/test_clean.wav")


/tmp/ipython-input-3852858702.py:5: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sr = librosa.load(audio_path, sr=16000)


FileNotFoundError: [Errno 2] No such file or directory: '/content/test_clean.wav'

In [ ]:
!ls /mnt/data


ls: cannot access '/mnt/data': No such file or directory


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving testone.wav to testone.wav


In [ ]:
!ls /content


drive  sample_data  testone.wav


In [ ]:
!apt-get -y install ffmpeg


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.


In [ ]:
!ffmpeg -y -i /content/sample.wav -ac 1 -ar 16000 /content/test_clean.wav


ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

In [ ]:
!ls /content


drive  sample_data  testone.wav


In [ ]:
predict_emotion("/content/testone.wav")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step
Predicted Emotion: happy
Confidence: 0.99989617


np.str_('happy')